##TASK 1

Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
3
45
83
21
Have a go at ‘w’ ‘r’  ‘a’


In [144]:
#Create a text file Numbers.txt if not in existence. set it to write mode "w"
with open("Numbers.txt","w") as numbers:
    count=0
    while count<4:
        input_number=int(input(f"Enter the number {count+1}: "))
        numbers.write(str(input_number))
        numbers.write('\n')
        count+=1

numbers.close()

#Read the Numbers.txt File created above and output it on the screen
readFile=open("Numbers.txt","r")
strFile=readFile.read()
print(strFile)

89
90
67
45



##TASK 2

Write a program to ask a student for their percentage mark and convert this to a grade.
The conversion will be done in a function called mark_grade 

In [164]:
#Function to accept student percentage mark and return the grade equivalent
def mark_grade(percentage_mark):
    if percentage_mark >=80 and percentage_mark<=100:
        grade="A"
    elif percentage_mark >=70 and percentage_mark<80:
        grade="B"
    elif percentage_mark >=60 and percentage_mark<70:
        grade="C"
    elif percentage_mark >=50 and percentage_mark<60:
        grade="D"
    elif percentage_mark >=40 and percentage_mark<50:
        grade="E"
    elif percentage_mark >=0 and percentage_mark<40:
        grade="F"
    else:
        grade="Percentage Mark not in range of \"0 - \"100"
    
    return grade

#Accept student target Grade
target_grade=input("Please enter your target Grade A, B, C, D, E, F: ") #TASK 2 EXTENSION 

#Accept student percentage mark or exam score
input_mark=int(input("Please enter your percentage mark: "))

#this send the percentage mark to the function mark_grade and the grade is returned and store it in "grade"
grade=mark_grade(input_mark)

#Print percentage mark and its equivalent grade
print(f"Your percentage_mark of {input_mark} is graded: \"",grade,"\"") 

Your percentage_mark of 85 is graded: " A "


In [165]:
#TASK 2 EXTENSION 
#This function accept a student target grade and return the grade's numeric order
def convert_grade_to_number(grade): 
    if grade=="A":
        priority=6
    elif grade=="B":
        priority=5
    elif grade=="C":
        priority=4
    elif grade=="D":
        priority=3
    elif grade=="E":
        priority=2
    elif grade=="F":
        priority=1
    else:
        priority=0
    return priority

#This converts target grade and actual exam grade to numeric equivalent, then compare the the two values 
if int(convert_grade_to_number(target_grade))!=0:
    if int(convert_grade_to_number(target_grade))>int(convert_grade_to_number(grade)):
        print("Sorry, You need to put more effort next time. \nYour Target grade was: \" ",target_grade,"\"\nbut your Final Exam grade is: \"",grade,"\"-->",input_mark)
    elif int(convert_grade_to_number(target_grade))==int(convert_grade_to_number(grade)):
        print("You have achieved your set goal. \nYour Target grade was: \" ",target_grade,"\"\nand your Final Exam grade is: \"",grade,"\"-->",input_mark)
    elif int(convert_grade_to_number(target_grade))<int(convert_grade_to_number(grade)):
        print("You have performed excellently well above your set goal. \nYour Target grade was: \" ",target_grade,"\"\nbut your Final Exam grade is: \"",grade,"\"-->",input_mark)
    else:
        pass
else:
    print("Check your Target grade input! \nYour Target grade was: ",target_grade)

You have performed excellently well above your set goal. 
Your Target grade was: "  B "
but your Final Exam grade is: " A "--> 85


##TASK 3

Create a 1D array of numbers from 0 to 9

In [166]:

import numpy as np

#Create a 1 dimensional array that contains 0 to 9
oneD_array=np.arange(10)

print(oneD_array)

[0 1 2 3 4 5 6 7 8 9]


##TASK 4

Create a 3×3 NumPy array of all Boolean value Trues

In [167]:
import numpy as np

#created a 2 dimensional array with boolean value of TRUE
numpy_arr4bool=np.array([True,True,True,True,True,True,True,True,True]).reshape(3,3)
print(numpy_arr4bool,"\n")

#OR
#created a 2 dimensional array with boolean value of TRUE
numpy_arr4True=np.full((3,3),True)
print(numpy_arr4True,"\n")

#OR
#created a 2 dimensional array with boolean value of TRUE
numpy_array4True=np.ones(9,dtype=bool)
print(numpy_array4True.reshape(3,3),"\n")


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 



##TASK 5

Extract all odd numbers from array of 1-10

In [200]:
import numpy as np

#created an array begining with 1 and increases by 2: 1, 1+2, 1+2+2, 1+2+2+2
arr_odd=np.arange(1,10,2)
print("First Method: ",arr_odd)

#OR
#created an array begining with 1 and increases by 2: 1, 1+2, 1+2+2, 1+2+2+2
arr_odd2=np.arange(1,10)
print("Second Method: ",arr_odd2[::2])

First Method:  [1 3 5 7 9]
Second Method:  [1 3 5 7 9]


##TASK 6

Replace all odd numbers in an array of 1-10 with the value -1

In [172]:
import numpy as np

#created an array of 10 numbers
arr_odd=np.arange(1,11)

print(arr_odd)

print("\n1st Method")
#loop through the list to check for odd numbers
for i in range(len(arr_odd)):
    if arr_odd[i]%2==1:#if remainder is 1 then the number is an odd number
        arr_odd[i]=-1  #replace the odd number with -1

print(arr_odd)

#OR

print("\n2nd Method")
arr_odd2=np.arange(1,11)
arr_odd2 [arr_odd2%2==1]=-1
print(arr_odd2)

#OR

print("\n3rd Method")
arr_odd3=np.arange(1,11)
arr_odd3[::2]=-1 #OR arr_odd3[0::2]=-1 
print(arr_odd3)


[ 1  2  3  4  5  6  7  8  9 10]

1st Method
[-1  2 -1  4 -1  6 -1  8 -1 10]

2nd Method
[-1  2 -1  4 -1  6 -1  8 -1 10]

3rd Method
[-1  2 -1  4 -1  6 -1  8 -1 10]


##TASK 7

Convert a 1D array to a 2D array with 2 rows

In [175]:
import numpy as np

oneDim_array2=np.arange(20,30)
print("One dimensional Array: \n",oneDim_array2,"\n converted to:")
twoDim_array2=oneDim_array2.reshape(2,5)
print("Two dimensional Array: \n",twoDim_array2,"\n")

#OR
oneDim_array3=np.arange(20,30).reshape(2,-1)
print("Two dimensional Array: \n",oneDim_array3)

One dimensional Array: 
 [20 21 22 23 24 25 26 27 28 29] 
 converted to:
Two dimensional Array: 
 [[20 21 22 23 24]
 [25 26 27 28 29]] 

Two dimensional Array: 
 [[20 21 22 23 24]
 [25 26 27 28 29]]


##TASK 8

Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals


In [197]:
import numpy as np

array_A=np.random.randint(1,99,(5,5))
array_B=np.random.randint(1,99,(5,5))

print("Array A: \n",array_A,"\n")
print("Array B: \n",array_B,"\n")

array_C=np.dot(array_A,array_B)
print("Array C: \n",array_C,"\n")


Array A: 
 [[47 97 98 30 38]
 [52 59 82 42 32]
 [14 44 44  5 88]
 [14 14 36 55 15]
 [29 14 13 53 27]] 

Array B: 
 [[15 50 46 98 44]
 [42 45 20 82 52]
 [38 25 11 74 18]
 [64 89 89 88 85]
 [43 66 36 17 69]] 

Array C: 
 [[12057 14343  9218 23098 14048]
 [10438 13155  9364 20242 12610]
 [ 7834 10033  5621 10172 10193]
 [ 6331  8115  6755 10279  7702]
 [ 6070  8904  7446 10075  8606]] 



In [198]:

sumC=np.sum(array_C)
print("Array SUM: \n",sumC,"\n")

rowsTotal=np.sum(array_C,axis=1)
print("Row SUM: \n",rowsTotal,"\n")

columnsTotal=np.sum(array_C,axis=0)
print("Column SUM: \n",columnsTotal,"\n")

Array SUM: 
 262709 

Row SUM: 
 [72764 65809 43853 39182 41101] 

Column SUM: 
 [42730 54550 38404 73866 53159] 



In [199]:
arrayAB_stacked=np.vstack((array_A,array_B))
arrayAB_stacked

array([[47, 97, 98, 30, 38],
       [52, 59, 82, 42, 32],
       [14, 44, 44,  5, 88],
       [14, 14, 36, 55, 15],
       [29, 14, 13, 53, 27],
       [15, 50, 46, 98, 44],
       [42, 45, 20, 82, 52],
       [38, 25, 11, 74, 18],
       [64, 89, 89, 88, 85],
       [43, 66, 36, 17, 69]])

##TASK 9

Create the following pattern without hardcoding. Use only NumPy  functions.
array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3])

In [196]:
import numpy as np

arrayOnes=np.ones(3)
print("Arrays of ones: ",arrayOnes)

arrayTwos=np.ones(3)*2
print("Arrays of twos: ",arrayTwos)

arrayThrees=np.ones(3)*3
print("Arrays of threes: ",arrayThrees)

array123=np.tile([1,2,3],3)
print("Repeating 1,2,3: ",array123)

allCombined=np.hstack((arrayOnes,arrayTwos,arrayThrees,array123))
print(allCombined)

Arrays of ones:  [1. 1. 1.]
Arrays of twos:  [2. 2. 2.]
Arrays of threes:  [3. 3. 3.]
Repeating 1,2,3:  [1 2 3 1 2 3 1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


##TASK 10

In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b

In [186]:
import numpy as np

empty=[]
firstArray=np.array([1,2,3,4,5])
secondArray=np.array([4,5,6,7,8,9])

for i in range(len(firstArray)):
     for j in range(len(secondArray)):
         if int(firstArray[i])==int(secondArray[j]):
            empty.append(j) #get all the positions where item in secondArray is contained in firstArray

            
secondArray=np.delete(secondArray,empty) #delete from second array item whose positions are stored in empty
print("Array a: ",firstArray, "\nArray b: " , secondArray)


#NOTE UNION can also be used...
# list1 = np.array(list(range(1,6)))
# list2 = np.array(list(range(4,10)))
# list3 = np.union1d(list1, list2)
# print(list3)
#from3to7items= list3[2:7]
#print(f"items 3 to 7: {items3to7},  Total is : {np.sum(from3to7items)}" )

Array a:  [1 2 3 4 5] 
Array b:  [6 7 8 9]


##TASK 11

Get all items between 3 and 7 from a and b and sum them together

In [188]:
stackAandB=np.hstack((firstArray,secondArray))
print(stackAandB)
print("Range to sum: ",stackAandB[2:7])
print("Sum of the above array: ",np.sum(stackAandB[2:7]))

[1 2 3 4 5 6 7 8 9]
Range to sum:  [3 4 5 6 7]
Sum of the above array:  25
